#Lesson 4
#
# Page : 40/179
#
import os
os.chdir("J:\Education\Code\DATA_Science\Books\Jason_Brownlee\Machine-Learning-Mastery-With-Python\Part_II\Lesson4")
def load_data():
    from pandas import read_csv
    filename = "pima-indians-diabetes.data.csv"
    col_names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
    data = read_csv(filename, names = col_names)
    return data#returs "pima-indians-diabetes.data.csv" as a Pandas dataframe with the cols named as in col_names

def data_peek():
    '''view first 20 rows'''
    data = load_data()
    peek = data.head(20)
    return peek# returns a dataframe with 20 rows for quick viewing

def data_dimensions():
    '''View the data dimensions'''
    data = load_data()
    shape = data.shape
    return shape#returns the dimensions of data

def data_datatypes():
    '''View the data types present in the data'''
    data = load_data()
    types = data.dtypes
    return types#returns the data types present

def data_description():
    '''View the statistical descriptio of the data'''
    from pandas import set_option
    data = load_data()
    set_option('max_columns', 200)
    set_option('max_rows',1000)
    set_option('precision', 3)
    description = data.describe()
    return description#return the sattistical description of the data

def data_class_distribution():
    '''View the class distribution of the data'''
    from pandas import set_option
    data = load_data()
    set_option('precision', 3)
    class_counts = data.groupby('class').size()
    return class_counts#retuns the class distribution of the data

def data_correlations():
    '''View the data correlation materix generated by calculating the Pearson's Correlation Coefficient'''
    from pandas import set_option
    data = load_data()
    set_option('precision', 3)
    correlations = data.corr(method = 'pearson')
    return correlations#returns the correlation matric

def data_skew():
    '''View the skew matrix for data variables'''
    data = load_data()
    skew = data.skew()
    return skew#return the skew matrix